### ISSUE TITLE
Add documentation?

### ISSUE THREAD

**Issue by coisnepe** [auth0/ruby-auth0#102]
I really want to use auth0 for a pet project, but I'm pulling my hair out trying to figure out how this gem needs to be used...
Perhaps you could at least add a link to the [rubydoc repo](http://www.rubydoc.info/github/auth0/ruby-auth0/toplevel). I also don't understand why the examples don't actually use auth0...

**Comment by joshcanhelp** [comment]
@coisnepe - Apologies for the confusion here and the long delay in response. I'm working on updating our README now and will have a more complete set of instructions for everyone merged this week. There is a linked badge at the top pointing to the link you mentioned but it's easy to skip over. 

If you have any specific questions, please feel free to post in the [Auth0 Community](https://community.auth0.com/tags/ruby) and add the tag `ruby`,
