### ISSUE TITLE
Cannot refresh access token with refresh token.

### ISSUE THREAD

**Issue by dotmartyr** [auth0/ruby-auth0#111]
It would appear the `login` function in `authentication_endpoints.rb`, which POSTs to `oauth/token` does not appear to allow for an optional refresh token field. 

According to the Auth0 docs, this endpoint is also used to get a new access token via refresh token if one is available (using `refresh_token` in the `grant_field` option as well as providing the `refresh_token` as a top level param). 

To me, this means that there is no way to use a refresh token to get a new access token with this API wrapper.

Is this correct?

**Comment by joshcanhelp** [comment]
Apologies for the late reply here ... yes, that is correct in the current implementation. We're currently overhauling the auth endpoints module here, though, and will make sure to add the capability to do that.
