### ISSUE TITLE
signin with referral token

### ISSUE THREAD

**Issue by nitsx2** [auth0/ruby-auth0#127]
hy, i want to login with auth0 but also want to save referral token which is coming in url(myweb.com?referral=xxxx). 
 Is there anyway to achieve this??

**Comment by joshcanhelp** [comment]
@nitsx2 - Thanks for the report here. Can you clarify what you're trying to do? I'm not familiar with the `referral` URL parameter.

**Comment by nitsx2** [comment]
Actually we are using auth0 for signup/login process in my shopping website.Now we want to add a functionality in it that if user signup with given referral code/promo_code then we will give him extra bonus points to purchase things. Referral token will come with website url(website.com?referral=abcd).
And this url will go directly to my auth0(mydomain.auth0.com) for signup/login . I want to send this url to auth0 for signup and get back it after user signup successfully. Is it possible?

**Comment by joshcanhelp** [comment]
@nitsx2 - Since this is a question on usage rather than an issue with the SDK, could I ask you to make a post on our [Community site](https://community.auth0.com/tags/ruby)? Here are a few existing threads that might be helpful:

- https://community.auth0.com/t/passing-config-to-hosted-login-page/8073
- https://community.auth0.com/t/configuring-config-for-hosted-login-page/8287

**Comment by devstarkes** [comment]
> Actually we are using auth0 for signup/login process in my shopping website.Now we want to add a functionality in it that if user signup with given referral code/promo_code then we will give him extra bonus points to purchase things. Referral token will come with website url(website.com?referral=abcd).
> And this url will go directly to my auth0(mydomain.auth0.com) for signup/login . I want to send this url to auth0 for signup and get back it after user signup successfully. Is it possible?

@nitsx2 Have you found anything?

**Comment by nitsx2** [comment]
Thanks solved😁😁

**Comment by xinars** [comment]
> 

How is this solved? I wasn't able to find anything on this.
