### ISSUE TITLE
New Release with Client Token work

### ISSUE THREAD

**Issue by samjonester** [auth0/ruby-auth0#148]
Would it be possible to release a new version of this library with the work done in #129 (and subsequent fixes I see on master)? Is the library in a state where it is able to be released?

Thanks!

**Comment by joshcanhelp** [comment]
@samjonester - Sorry for the delay here! I was waiting for responses on the [open PRs](https://github.com/auth0/ruby-auth0/pulls) but I lost track of time. I'll package up what we have so far and release this week. Thank you for the ping!

**Comment by joshcanhelp** [comment]
@samjonester - Apologies for the delay here, I thought we'd be able to get the last PR merged but that didn't happen. I'll push this out first thing Monday. I appreciate your patience!

**Comment by samjonester** [comment]
Thanks @joshcanhelp!
