### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by dentarg** [auth0/ruby-auth0#15]
Dedicate an auth0 account for tests, keys can be encrypted in .travis.yml, write tests that actually do stuff with the API. 

What do you think?

**Comment by jfromaniello** [comment]
Yes, it make sense @hzalaz will look into this.. thank for all your feedback

**Comment by dentarg** [comment]
@hzalaz I noticed https://github.com/auth0/ruby-auth0/commit/6e19b8f032e350723856c1bacec58739fe52082a 

> When 2 builds run in parallel, they clash with each other.

I think the answer is https://github.com/vcr/vcr

GitHub uses it for their API client, you can read about it at https://github.com/octokit/octokit.rb#running-and-writing-new-tests

**Comment by dentarg** [comment]
> I think the answer is https://github.com/vcr/vcr

...not to remove number of Ruby versions to test against

**Comment by hzalaz** [comment]
I know about vcr but in my experience the recorded tests will get outdated easily and everything will seem ok when it shouldn't, that's the reason I'd rather hit the API directly for integration tests. Also we're already mocking http in unit tests (I'd rather use them there) so both test will be exactly the same.

I want to rework the "new tests" to avoid clashing with each other (like prefixing ids) but until then I prefer a reliable build.

**Comment by dentarg** [comment]
I understand. Nice work on this!

**Comment by hzalaz** [comment]
We don't have all endpoints tested against the real API but at least we have most of /users which should be the most used. We'll continue to add more endpoints eventually. PR are welcome! :smile:
