### ISSUE TITLE
No method to get all resource servers

### ISSUE THREAD

**Issue by philomory** [auth0/ruby-auth0#154]
### Description

There's no method in the gem to get a list of all resource servers (e.g. to call `GET /api/v2/resource-servers`); corresponding methods exist for other endpoints such as Clients.

I have a PR ready to implement this change, but the contributing guidelines instruct to open an issue first, so, that's what I'm doing.

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation ([repo README](https://github.com/auth0/ruby-auth0/blob/master/README.md) or [Quickstart](https://auth0.com/docs/quickstart/backend/rails))?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository? See also the [OmniAuth-Auth0 strategy](https://github.com/auth0/omniauth-auth0) for logging in with Rails.
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/ruby-auth0/issues) or [PRs](https://github.com/auth0/ruby-auth0/pulls) for this issue?

### Environment

Please provide the following:

* Ruby Auth0 version: 4.6.0
* Ruby version: 2.4.4p296
* Rails version (if applicable): N/A
* Browser version (if applicable): N/A
* Additional gems that might be affecting your instance: N/A

### Reproduction

```
irb(main):001:0> connection = Auth0::Client.new(...)
irb(main):002:0> apis = connection.resource_servers
NoMethodError: undefined method `resource_servers' for #<Auth0::Client:0x0000000002e740a8>
Did you mean? resource_server
```

**Comment by joshcanhelp** [comment]
Thank you @philomory! We'd be glad to accept a PR for this. A few things to keep in mind when you put this together:

- Unit tests should be included, go ahead and use one of the other endpoints as a template for that. 
- Integration tests are appreciated but not required. If you do tackle integration tests, you'll need to uncomment [this line](https://github.com/auth0/ruby-auth0/blob/master/spec/spec_helper.rb#L25) so VCR can make an HTTP recording. Once everything is working and passing, comment it out again and run the tests once more to make sure no HTTP connections are made.

**Comment by philomory** [comment]
So, I've written unit tests based on the existing tests for other endpoints, and I've written what I believe will be appropriate integration tests, but as far as I can tell it's impossible for me to successfully run the integration tests without some configuration data that isn't available to me (specifically I think it's the info needed to access the auth0-sdk-tests account). Is there any documentation on running the integration tests? When I run `bundle exec rake integration` they all fail, across the board.

**Comment by joshcanhelp** [comment]
@philomory - I really need to have some contribution docs in here ... again, apologies for the gap there.

All you need is a `.env` file in the gem folder with:

- `DOMAIN`
- `CLIENT_ID`
- `CLIENT_SECRET`
- `MASTER_JWT`

... for a test Application that is authorized for the Management API. All the other tests will use HTTP recordings but your tests will run live. 

That said, feel free to just put through the PR and let CI run the tests for you with our stored credentials!

Thanks again!
