### ISSUE TITLE
No method to update/patch resource servers

### ISSUE THREAD

**Issue by philomory** [auth0/ruby-auth0#156]
### Description
There's no method in the gem to update a resource server (e.g. to call PATCH /api/v2/resource-servers/[id]); corresponding methods exist for other endpoints such as Clients.

I have a WIP PR for this.

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation ([repo README](https://github.com/auth0/ruby-auth0/blob/master/README.md) or [Quickstart](https://auth0.com/docs/quickstart/backend/rails))?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository? See also the [OmniAuth-Auth0 strategy](https://github.com/auth0/omniauth-auth0) for logging in with Rails.
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/ruby-auth0/issues) or [PRs](https://github.com/auth0/ruby-auth0/pulls) for this issue?

### Environment

Please provide the following:

* Ruby Auth0 version: 4.6.0
* Ruby version: 2.4.4p296
* Rails version (if applicable): N/A
* Browser version (if applicable): N/A
* Additional gems that might be affecting your instance: N/A

### Reproduction

```
irb(main):001:0> connection = Auth0::Client.new(...)
irb(main):002:0> connection.patch_resource_server(...)
NoMethodError: undefined method `patch_resource_servers' for #<Auth0::Client:0x00000000073974a0>
```

**Comment by joshcanhelp** [comment]
@philomory - Appreciate the help with these! You are approved to proceed 😃

**Comment by joshcanhelp** [comment]
Merged!
