### ISSUE TITLE
Not enough information in exception when Rate Limiting is encountered

### ISSUE THREAD

**Issue by philomory** [auth0/ruby-auth0#158]
### Description

When rate limiting is encountered, an `Auth0::Unsupported` exception is raised, whose message only states `{"statusCode":429,"error":"Too Many Requests"}`. This is because the exception message is generated from only the HTTP response's status and body.

When the Auth0 API returns a 429 response, it includes details about the limits in HTTP response headers; specifically, as noted in [Rate Limits](https://auth0.com/docs/policies/rate-limits#http-response-headers), the `X-RateLimit-Limit`, `X-RateLimit-Remaining` and `X-RateLimit-Reset` headers.

It would be good to return this information to the caller when raising an exception due to rate limiting.

### Prerequisites

* [x] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [x] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [x] Did you check the documentation ([repo README](https://github.com/auth0/ruby-auth0/blob/master/README.md) or [Quickstart](https://auth0.com/docs/quickstart/backend/rails))?
* [x] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [x] Are you reporting this to the correct repository? See also the [OmniAuth-Auth0 strategy](https://github.com/auth0/omniauth-auth0) for logging in with Rails.
* [x] Are there any related or duplicate [Issues](https://github.com/auth0/ruby-auth0/issues) or [PRs](https://github.com/auth0/ruby-auth0/pulls) for this issue?

### Environment

Please provide the following:

* Ruby Auth0 version: 4.6.0
* Ruby version: 2.4.4
* Rails version (if applicable): N/A
* Browser version (if applicable): N/A
* Additional gems that might be affecting your instance: N/A

### Reproduction

Easiest way to reproduce is to use a free/trial account with a low rate limit, and then repeatedly call `Auth0::Api::V2#logs` until an exception is raised.

**Comment by philomory** [comment]
Actually, it might be generally a good idea to make all of the exceptions that `Auth0::Mixins::HTTPProxy` can raise, inherit from a common `Auth0::HTTPError`, and provide access to either the `RestClient::ExceptionWithResponse` or at least the `RestClient::Response` object in addition to the normal message.

**Comment by joshcanhelp** [comment]
@philomory - Apologies for not responding any sooner here, I don't recall getting a notification for this. 

Thank you for the report here and digging into a potential solution. I'll see if I can get a good solution in place ahead of our next release.

**Comment by joshcanhelp** [comment]
Fixed in #170
