### ISSUE TITLE
Typo in AuthenticationEndpoints.login

### ISSUE THREAD

**Issue by johnpash** [auth0/ruby-auth0#17]
It looks like there is a typo in the [AuthenticationEndpoints.login method](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/authentication_endpoints.rb#L36).

```ruby
grand_type: "password",
```
should be:
```ruby
grant_type: "password",
```

Also,  [the spec](https://github.com/auth0/ruby-auth0/blob/master/spec/lib/auth0/api/authentication_endpoints_spec.rb#L30) has the same issue.

I'm able to use the **login** method with no problems, so maybe "password" is the default grant_type and this param is ignored?

**Comment by hzalaz** [comment]
Fixed by #22
