### ISSUE TITLE
Mismatch between create_user method implementation and endpoint

### ISSUE THREAD

**Issue by MissingHandle** [auth0/ruby-auth0#171]
### Description

The endpoint for creating a user lists the name field as optional:

https://auth0.com/docs/api/management/v2#!/Users/post_users

But the `create_user` method requires a name parameter:

https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/v2/users.rb#L48

I would think the implementation of the gem should match the reality of the endpoint. For instance, perhaps `connection` should be a positional or required named parameter since it is required.

### Prerequisites

* [ ] I have read the [Auth0 general contribution guidelines](https://github.com/auth0/open-source-template/blob/master/GENERAL-CONTRIBUTING.md)
* [ ] I have read the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md)
* [ ] Did you check the documentation ([repo README](https://github.com/auth0/ruby-auth0/blob/master/README.md) or [Quickstart](https://auth0.com/docs/quickstart/backend/rails))?
* [ ] Did you check the [Auth0 Community](https://community.auth0.com/)?
* [ ] Are you reporting this to the correct repository? See also the [OmniAuth-Auth0 strategy](https://github.com/auth0/omniauth-auth0) for logging in with Rails.
* [ ] Are there any related or duplicate [Issues](https://github.com/auth0/ruby-auth0/issues) or [PRs](https://github.com/auth0/ruby-auth0/pulls) for this issue?

### Environment

* Ruby Auth0 version: master

**Comment by joshcanhelp** [comment]
@MissingHandle - I agree, that's not ideal for this method. Changing it, however, would require a breaking change. Let me think about what we can do here and get back to you.

**Comment by MissingHandle** [comment]
@joshcanhelp -- breaking changes would seem to imply a sem-ver major bump. Are there reasons to not do one?

**Comment by MissingHandle** [comment]
For the record, my workaround is:

```ruby
UsersPath = "/api/v2/users"
# ...
auth0_client.post(UsersPath,
  connection: AgentServices::Constants::Auth0DbConnectionName,
 #...
)
```

**Comment by joshcanhelp** [comment]
@MissingHandle - We wouldn't typically release a major just to adjust the behavior of a single method. That said, we've got a few other things that need to be addressed in a major release. I'll tag this with a `5.0.0` milestone to make sure we don't lose track of it.
