### ISSUE TITLE
Token required even when not necessary

### ISSUE THREAD

**Issue by MicMicMon** [auth0/ruby-auth0#190]
The gem requires the token to be non-null (see [this line](https://github.com/auth0/ruby-auth0/blob/4e03ea73575dfde3ea263ecbec451d97b908e62e/lib/auth0/mixins/initializer.rb#L44)), whereas it is useful to use the API (specifically [those helpers](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/authentication_endpoints.rb)) just to **actually get** a management token - and thus with a nil token to begin with.

I have this workaround for now, but that would be great to provide a canonical way (or maybe there is and I didn't think of it?):
```ruby
# Get a brand new management token for this machine to machine app
Auth0Client.new(
        client_id: Rails.application.secrets.auth0_client_id,
        client_secret: Rails.application.secrets.auth0_api_mtom_client_secret,
        domain: Rails.application.secrets.auth0_domain,
        token: 'dummy-but-must-be-non-null-because-of-the-gem'
      ).api_token
```

**Comment by MicMicMon** [comment]
Also discussed here: https://github.com/auth0/ruby-auth0/issues/86 - but added this issue anyway as a feature request.

**Comment by MicMicMon** [comment]
Ah yes, thanks for the idea.

Still, I'm not so keen on pulling chunks of code from a gem - that might change - inside my own code. Specifying `state` also smells like stuff that should be hidden from the library user IMO (and `scope` does not seem necessary in my use case).

Offering this hassle-free token creation through a Singleton-like class would be a very nice wrapper I think.

**Comment by MicMicMon** [comment]
Yes ok I get it, it just pulls much more than I actually need into my own object - which I don't like that much. I prefer having a specific object outside that does not impact my own object signature.

Sorry I wasn't clear: I need a token **once I get it**. My need is:

1. **Get a Management API v2 token**
2. **Use it with calls and such**

Thus, a singleton object that achieves step 1 would be nice. That would replace `mtom_api_token` in the code I came up with:

```ruby
  class Auth0ManagementAPI
    include Singleton

    def auth0_api
      @auth0_api ||= Auth0Client.new(
        client_id: Rails.application.secrets.auth0_client_id,
        domain: Rails.application.secrets.auth0_domain,
        token: mtom_api_token.access_token,
        api_version: 2
      )
    end

    # Return a fresh token for the Backend to interact with the Auth0 Management
    # API
    #
    # @return [ApiToken]
    def mtom_api_token
      Auth0Client.new(
        client_id: Rails.application.secrets.auth0_client_id,
        client_secret: Rails.application.secrets.auth0_api_mtom_client_secret,
        domain: Rails.application.secrets.auth0_domain,
        token: 'dummy-but-must-be-non-null-because-of-the-gem'
      ).api_token
    end
```

Then I simply use it (that's only then that I need the token):

```ruby
    # Updates user metadata (the user typically can modify this metadata through
    # the UI).
    #
    # @param [String] user_id
    # @param [Hash] user_metadata
    #
    # @return [Hash] Updated user profile from Auth0
    def update_user_metadata(user_id, user_metadata)
      # Clears first, otherwise merges only
      auth0_api.patch_user(user_id, user_metadata: {})
      auth0_api.patch_user(user_id, user_metadata: user_metadata)
    end
```

Hope it's more clear that way.

It's definitely ok, I was just suggesting an improvement for the gem API - or maybe I don't know some classic pattern that you normally use in that case. Including the gem code inside my methods seems anti-pattern to me but I could well be wrong.

**Comment by MicMicMon** [comment]
There must be something I don't understand. What do you mean by "the token that's automatically retrieved"?

If I replace my `auth0_api` with what I understand from your message:
```ruby
def auth0_api
      @auth0_api ||= Auth0Client.new(
        client_id: Rails.application.secrets.auth0_client_id,
        domain: Rails.application.secrets.auth0_domain,
        # token: mtom_api_token.access_token,
        api_version: 2
      )
    end
```
I sure get this: `Auth0::InvalidCredentials (Must supply a valid API token)` (which makes sense to me), the gem doesn't automatically generate a token.

That's why I generate a token in the first place, following the instructions [here](https://auth0.com/docs/api/management/v2/get-access-tokens-for-production).

What am I missing here?
Thanks for your time!

**Comment by MicMicMon** [comment]
Awesome, thanks for the clarification!
Works like a charm indeed.
Nice.

(I leave it open for you to close when you're comfortable)

**Comment by MicMicMon** [comment]
Sorry, didn't look at it until now. That's great, it is now totally clear I think :)
Thanks for your attention.

**Comment by CesarOliveira** [comment]
@qortex and @joshcanhelp sorry to bring this up again.

I'm trying to use the `start_passwordless_email_flow` method, to do that I have to insatiate a new `auth0_client`

But when I do that with my `client_id` and `client_secret` for my application I got:
````
Auth0::AccessDenied (
 {
  "error":"unauthorized_client", 
  "error_description":"Grant type 'client_credentials' not allowed for the client.",
  "error_uri":"https://auth0.com/docs/clients/client-grant-types"
 }
)
````

But to use the `start_passwordless_email_flow` through the Auth0 API I don't need the `Client Credentials` enabled in the application.

So I have two options:

1. Use the `Machine to Machine` credentials to generate a access_token and then create a new client with that token and the `client_id` of my application that the `Client Credentials`;

2. Insatiate a client with the token empty like this: 
````
      auth0_client = Auth0Client.new(
        client_id: ENV.fetch('AUTH0_CLIENT'),
        domain: ENV.fetch('AUTH0_DOMAIN'),
        token: '' # or 'anything in here lik sugested by qortex'
      )
````

My question is, there is a better way to do that to use the `start_passwordless_email_flow` that doesn’t require having a client_secret?
