### ISSUE TITLE
Missing to_json for delete_with_body

### ISSUE THREAD

**Issue by qortex** [auth0/ruby-auth0#193]
# Issue
When using `#remove_role_permissions`, I get:
```
warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload
Auth0::BadRequest: {"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Expected type string but found type array' on property permissions[0].resource_server_identifier (The resource server that the permission is attached to). (also) Payload validation error: 'Expected type string but found type array' on property permissions[0].permission_name (The name of the permission to perform the action).","errorCode":"invalid_body"}
```
even though my array looks fine to me:
```
[
    [0] #<Struct:Permission:0x5586cd6267a0
        permission_name = "users:read:co_members",
        resource_server_identifier = "https://xxx/v1/"
    >,
    [1] #<Struct:Permission:0x5586cd626688
        permission_name = "users:read:current_user",
        resource_server_identifier = "https://xxx/v1/"
    >
]
```
# Fix
In my understanding, it is due to the fact that [this line](https://github.com/auth0/ruby-auth0/blob/279093e2802b898f8b19ffa5ace53963e3265f3a/lib/auth0/mixins/httpproxy.rb#L24) uses `body` instead of `body.to_json`.

That would be an easy fix if it's ok.

**Comment by MicMicMon** [comment]
I confirm the issue & the fix, doing the request myself by hand solves the issue:
```ruby
RestClient::Request.execute(
            method: :delete,
            url: "https://#{Rails.application.secrets.auth0_domain}/api/v2/roles/#{role_id}/permissions",
            headers: { 'Content-Type': 'application/json', Authorization: "Bearer #{access_token}" },
            payload: payload.to_json
          )
```

**Comment by joshcanhelp** [comment]
@MicMicMon - So ... I looked into this today in advance of a release and both with and without this change, integration tests pass (as long as you apply the fix to the integration test shown at the bottom of [this compare](https://github.com/auth0/ruby-auth0/compare/fix-users-integration-tests)). I don't see any _harm_ adding it but I'm worried there might be something else going on. 

Can you post some sample application code for the call using the SDK that is failing? And can you confirm that just changing that line as you suggested fixes the issue? I would like to see more explicitly how this is failing and be able to reproduce in tests before I merge any changes on this. 

Thank you!

**Comment by MicMicMon** [comment]
I don't have the code right at hand, but I will try.
I suspect things will go down as explained above, didn't change much. I still have the warning about the headers in my logs, but it works ok nonetheless.

Do the integration tests run against an actual auth0 tenant or a mockup? If it's a tenant, that's weird I had the issue in the first place.

**Comment by joshcanhelp** [comment]
The integration tests are recorded but I delete and re-run when making changes that might affect it. When a recording is **not** used (when they are deleted) then it runs on a live Auth0 tenant.

> I still have the warning about the headers in my logs, but it works ok nonetheless.

So this is just a warning, not a failure? Because I have that warning showing in tests as well. I think I misunderstood your issue here and thought it was a failure.

**Comment by MicMicMon** [comment]
And if you run the gem against a live tenant, you don't have the error I mentioned when using `remove_role_permissions`?

Sorry about the misleading statement about the warning: it shows up but it's ok, no issue.

The problem really is a blocking error (see 2nd log line in my initial post).

**Comment by joshcanhelp** [comment]
I get the warning but I don't get an error. If it helps, the integration test is [here](https://github.com/auth0/ruby-auth0/blob/master/spec/integration/lib/auth0/api/v2/api_roles_spec.rb#L134-L138) if you want to try running that as-is in your app.

**Comment by pebneter** [comment]
I'm observing the same issue. When removing roles from a user, I get a warning 
> warning: Overriding "Content-Type" header "application/json" with "application/x-www-form-urlencoded" due to payload
Applying @MicMicMon's suggested fix would solve the issue.

**Comment by MicMicMon** [comment]
Yeah, didn't take time to further test the stuff, but a fix would be nice as it still shows up in my logs too.

**Comment by joshcanhelp** [comment]
@pebneter @MicMicMon - thanks for checking back in here. We'll make sure to address this in the next release 👍

**Comment by MicMicMon** [comment]
Any visibility on the next release?

**Comment by MicMicMon** [comment]
@joshcanhelp Any news on this?

**Comment by joshcanhelp** [comment]
@MicMicMon - Apologies for the radio silence. No specific plans at the moment but if you can put together a PR here with tests to make sure that this doesn't break existing functionality, that would help things move along.

**Comment by joshcanhelp** [comment]
Wrong button :/

**Comment by qortex** [comment]
Did PR #212 , but couldn't figure out how test suite works :( Please let me know how I can have tests work to get PR merged.
