### ISSUE TITLE
Include prompts

### ISSUE THREAD

**Issue by qortex** [auth0/ruby-auth0#199]
Is there a roadmap to include prompts endpoints (new API feature) in the gem?
That would be awesome :)

**Comment by joshcanhelp** [comment]
Definitely on our radar! We'd like all SDKs to cover all the Management endpoints :)

**Comment by MicMicMon** [comment]
Hi @joshcanhelp , any timeframe for a release?

**Comment by joshcanhelp** [comment]
@MicMicMon - Nothing to share at the moment, unfortunately. We're open to PRs for all missing endpoints.

**Comment by MicMicMon** [comment]
Weird to close this feature request.

**Comment by joshcanhelp** [comment]
Thankfully there is a PR for this! 

Sorry for the poor communication here on my part. Lowering the overall number of open issues is something our team focuses on and that can lead to situations like this where it looks like we're saying "no" when in fact there isn't a path forward and an open issue here doesn't do much to help with that. Re-opening for now and we'll get this all out soon.

**Comment by MicMicMon** [comment]
ah great didn't see that actually!
Thanks for the update.

**Comment by Widcket** [comment]
This was solved by https://github.com/auth0/ruby-auth0/pull/205.
