### ISSUE TITLE
AuthenticationEndpoints should be independent of the V1/V2 API

### ISSUE THREAD

**Issue by sandrinodimattia** [auth0/ruby-auth0#20]
Currently the Auth API is only available in V1 mode: https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/mixins/initializer.rb#L19

But the Auth API is independent of our V1/V2 API, so it should also be available when working in V2 mode.

**Comment by Maxim-Filimonov** [comment]
:+1:

**Comment by hzalaz** [comment]
Fixed in #22
