### ISSUE TITLE
Permission Struct Conflicts with Model

### ISSUE THREAD

**Issue by sinor38058** [auth0/ruby-auth0#201]
Hi I'm using the latest gem version (4.9.0). When upgrading to this new version one of my Permission model fails to load. 

When I open up rails console and start calling methods on it, it fails as it attempts to call methods on this struct instead https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/mixins/permission_struct.rb.

I can run `Object.send(:remove_const, :Permission)` and use my model as expected.

**Comment by MicMicMon** [comment]
Ah, must be linked to #196 which fixes #192

**Comment by MicMicMon** [comment]
It seems best would be to put all classes under an `Auth0` namespace, but that would be a breaking change.

**Comment by qortex** [comment]
Should not be closed.

**Comment by edwinthinks** [comment]
I just encountered this issue as well. Is there any other workarounds or then changing my own models to not use the name Permission?

**Comment by billmers** [comment]
Same issue here. Permission is a very common class name, would be nice if the auth0 struct was namespaced.
