### ISSUE TITLE
warning: URI.escape is obsolete

### ISSUE THREAD

**Issue by lostie** [auth0/ruby-auth0#202]
### Description

The `URI.escape` seems to be marked as obsolete:
https://ruby-doc.org/stdlib-2.7.0/libdoc/uri/rdoc/URI/Escape.html#method-i-escape-label-Description

and when running our Rails app or running the tests for it we're getting a lot of these warnings.

### Reproduction

When using the gem with Ruby 2.7 as part of a Rails app I get the following logs output:

```
.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/auth0-4.9.0/lib/auth0/mixins/httpproxy.rb:11: warning: URI.escape is obsolete
```

### Environment

- **Version of this library used:** 4.9.0
- **Version of the platform or framework used, if applicable:** Rails 6.0.2.1

**Comment by joshcanhelp** [comment]
@lostie - Thank you for the report! We'll get this fixed up and released soon.

**Comment by qortex** [comment]
Here is a discussion about that issue: https://stackoverflow.com/questions/2824126/whats-the-difference-between-uri-escape-and-cgi-escape

I'm not sure why `URI.escape` would be needed at all in the gem code here. It looks to me as it's just the URL part so doesn't need escaping - but maybe I'm missing some edge cases here.

From the SO post, the [Adressable](https://github.com/sporkmonger/addressable) gem is advised as a solution, but it would introduce a new dependency. Not sure it's worth it.

**Comment by qortex** [comment]
Tired of seeing these warnings in my logs, can we address this? Looks like the fix just needs a quick decision on which way to go.

**Comment by davidpatrick** [comment]
@qortex thanks for following up on this issue.  It looks like Addressable could be a sufficient replacement, my only concern is with this bit

```
The only problem left is that we didn't escape our query parameters properly, which brings us to the conclusion: we should 
not use a single method for the entire URI, because there is no perfect solution (so far). As you see & was not escaped from 
"My Blog & Your Blog". We need to use a different form of escaping for query params, where users can put different 
characters that have a special meaning in URLs. Enter URL encode. URL encode should be used for every "suspicious" 
query value, similar to what ERB::Util.url_encode does
```

> I'm not sure why URI.escape would be needed at all in the gem code here. It looks to me as it's just the URL part so doesn't need escaping - but maybe I'm missing some edge cases here.
The URL for GET requests would include query parameters that get the basic encoding talked about in that thread.

I currently don't have bandwidth to test the replacement, but anyone that wants to open a PR for this I would gladly review.

**Comment by davidpatrick** [comment]
Now that I have bandwidth for this, I will be picking this up this week.
