### ISSUE TITLE
Add User by ID example

### ISSUE THREAD

**Issue by szpasztor** [auth0/ruby-auth0#232]
### Describe the problem you'd like to have solved

A common use case when using the management API is to persist user data in the application's database. Currently, the required method for this can only be found by inspecting the gem's code [here](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/v2/users.rb#L69). An example with this method specifically would reinforce correct use of the API and be easier to understand.

**Comment by davidpatrick** [comment]
@szpasztor this is covered in the SDK docs here https://www.rubydoc.info/gems/auth0/4.4.0/Auth0/Api/V2/Users#user-instance_method is that not clear enough?

**Comment by davidpatrick** [comment]
Closing this issue for now
