### ISSUE TITLE
No way to get the decoded ID token

### ISSUE THREAD

**Issue by alexandrebini** [auth0/ruby-auth0#239]
Hi there,

Is there any specific reason why there is no way to get the decoded ID token? 

I'm asking because this could be refactored to handle that https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/mixins/validation.rb#L50-L51

**Comment by davidpatrick** [comment]
Hey @alexandrebini can you describe how you would like to access the token?  There is no particular reason not to expose it.

**Comment by davidpatrick** [comment]
Closing this issue for now
