### ISSUE TITLE
How to refresh VCR cassettes?

### ISSUE THREAD

**Issue by lostapathy** [auth0/ruby-auth0#255]
I've been working on #252 and #254, because we are trying to start using Auth0 and and already use rest-client 2.1 in our application.

I apologize if I missed the docs, but how does one setup the correct environment up so that they can delete the exist VCR cassettes and run the test suite against the real API?

**Comment by davidpatrick** [comment]
Hey @lostapathy to recreate the VCRS they need to be removed from https://github.com/auth0/ruby-auth0/tree/master/spec/fixtures/vcr_cassettes then configured here https://github.com/auth0/ruby-auth0/blob/a7ffeb50a095041bc3263aeb0de87cc02594d85a/spec/spec_helper.rb#L29-L33 we configure them with a private Auth0 client

**Comment by davidpatrick** [comment]
Let me know if there is something you need from us here
