### ISSUE TITLE
Add branding endpoints

### ISSUE THREAD

**Issue by Roriz** [auth0/ruby-auth0#262]
### Describe the problem you'd like to have solved
I want to consume and interact with all endpoints of: https://auth0.com/docs/api/management/v2#!/Branding/get_branding

### Describe the ideal solution
Ideally I want to consume something like:
 ```
auth0_client = Auth0Client.new(...)
auth0_client.branding_template!(html) # success
auth0_client.branding_template # liquid template
```

## Alternatives and current work-arounds
The current alternative is consume ruby-auth0 only to get token and interact with branding API with `net/http` gem

**Comment by davidpatrick** [comment]
https://github.com/auth0/ruby-auth0/pull/266

**Comment by Roriz** [comment]
Thank you
