### ISSUE TITLE
The dependency on addressable '~> 2.7.0' is forcing the usage of an insecure gem

### ISSUE THREAD

**Issue by cyclotron3k** [auth0/ruby-auth0#277]
The latest version of `ruby-auth0` has the following line in `auth0.gemspec`:

    s.add_runtime_dependency 'addressable', '~> 2.7.0'

Version 2.7.0 of `addressable` has recently had a CVE reported: https://github.com/advisories/GHSA-jxhc-q857-3j6g
And this version constraint makes it impossible to upgrade to the secure version (2.8.0)

Suggest using a more relaxed version constraint:

    s.add_runtime_dependency 'addressable', '~> 2.7'

**Comment by Widcket** [comment]
The `v5.1.2` release [is out](https://rubygems.org/gems/auth0/versions/5.1.2) now, which uses addressable `2.8.0`.
