### ISSUE TITLE
rest-client 2.1.0 support

### ISSUE THREAD

**Issue by Fitzsimmons** [auth0/ruby-auth0#286]
### Describe the problem you'd like to have solved

rest-client 2.1.0 was released in August 2019. The latest version of ruby-auth0 does not support it. This means that for projects that are already using the latest version of rest-client, the most recent supported version of ruby-auth0 is 4.8.0 (August 01, 2019)

### Describe the ideal solution

The latest version of rest-client is supported.

### For users of the auth0 gem:

* Stay on auth0 4.8.0 forever, missing out on any improvements
* Downgrade rest-client to 2.0.x in our project
* Switch to an alternative http client library in our project
* Fork ruby-auth0 and implement rest-client 2.1.0 support ourselves
* Abandon ruby-auth0 entirely

There are plenty of workaround options but they they have high development and/or maintenance costs relative to the benefits.

### For auth0

* Abandon rest-client in favour of Net::HTTP, eliminating the dependency on a gem that might have conflicts with gems already installed in client projects

**Comment by davidpatrick** [comment]
Hey @Fitzsimmons we would love to support rest-client 2.1.0 in the library.  There was a PR raised to bump the gem, but several tests were broken.  I currently don't have bandwidth to resolve the issue, but I should have some time coming up soon to investigate what the issue was.

**Comment by allison-strandberg** [comment]
@davidpatrick, any updates on this? Thank you!

**Comment by davidpatrick** [comment]
@allison-strandberg investigating this week! Thanks for the ping

**Comment by theirishpenguin** [comment]
Hi @davidpatrick, thanks for the fix. Would it be possible to push the 5.6.0 tagged release of auth0 to rubygems so that this restclient 2.1 update is available as an official version?
