### ISSUE TITLE
Remove or find maintainer for rest-client dependency

### ISSUE THREAD

**Issue by athix** [auth0/ruby-auth0#302]
The `rest-client` gem hasn't been touched in years, and the issue asking if anyone is still maintaining it has gone unanswered for months:

https://github.com/rest-client/rest-client/issues/764

Between this, and `rest-client` `v2.1.0` not following semver (minor version with breaking changes), I would highly recommend either removing it as a dependency, or finding someone on the Auth0 team willing to maintain the gem.

**Comment by ioquatix** [comment]
@stevehobbsdev Was there any movement on this? What about using Faraday?
