### ISSUE TITLE
Allow `code_verifier` to be passed to `exchange_auth_code_for_tokens` endpoint

### ISSUE THREAD

**Issue by mellowfish** [auth0/ruby-auth0#305]
### Describe the problem you'd like to have solved

We have PKCE code verification enabled in our tenant and there is no way to pass the `code_verifier` param to the `exchange_auth_code_for_tokens` endpoint, which causes otherwise valid requests to fail.

### Describe the ideal solution

It would be great if we could pass this parameter to this method.

## Alternatives and current work-arounds

We have extended this library in our rails app to allow us to overcome this issue. I can open a PR here if it would be desired, though I am curious (while I am here, as it were) if there are other "optional" params that tenants with specific configurations might need to pass. Would an `**optional_params` catch-all be better than enumerating all of them separately? If we have a list of all possible params for this endpoint, we could filter this `option_params` list to only those keys...

**Comment by stevehobbsdev** [comment]
Thanks for raising @mellowfish. Some thoughts on the above:

* We really should provide a way to provide `code_verifier` to support PKCE exchanges
* A catch-all parameter set would be beneficial but I would not limit it to a set of known params, as a developer can supply _custom_ parameters to that endpoint to run inside a [Rule](https://auth0.com/docs/rules)
* I think `code_verifier` specifically should be a first-class parameter on that method, and should be optional

Let me know if you're still happy to raise a PR for that, I will be happy to review.

**Comment by mellowfish** [comment]
Sounds good. I will try to get a PR open soon.

**Comment by mellowfish** [comment]
@stevehobbsdev now that people are back from the holidays, any chance of getting a review on that PR?

**Comment by stevehobbsdev** [comment]
Appreciate the patience here @mellowfish. A bit of a conversation has been generated internally about this feature across a couple of SDKs so we're engaged in working out whether we want to go beyond just the PR and implement additional support for PKCE. The PR itself looks good, just awaiting the outcomes of those conversations incase the API has to change a bit - hopefully not too long 👍🏻

**Comment by mellowfish** [comment]
That's fine. This isn't urgent for us either, but it would be nice to not maintain this patch locally for too long either.

**Comment by mellowfish** [comment]
@stevehobbsdev any update on this issue?

**Comment by stevehobbsdev** [comment]
@mellowfish Yes! We will be introducing an API that will allow you to pass `code_verifier` 🙌🏻  I don't have timelines yet, but soon. It's part of a bigger rollout as a few of our SDKs have a similar requirement, so we're batching the work.

Something else too, when looking into this work I found you can actually achieve this today by using a lower-level HTTP method provided by the library. It's not ideal I admit, but could be useful for others looking to do this before we improve the API in this area. Here's the gist of it:

```ruby
# Generate the code verifier. Must have no padding. This value should be stored for later
code_verifier = Base64.urlsafe_encode64(SecureRandom.hex(32), padding: false)

# Generate the code challenge using the code verifier. Again, must have no padding.
code_challenge = Base64.urlsafe_encode64(Digest::SHA256.digest(code_verifier), padding: false)

client = Auth0Client.new client_id: client_id,
	client_secret: <client secret>,
	domain: <domain>,
	redirect_uri: redirect_uri,
	additional_parameters: { 
		code_challenge: code_challenge,
		code_challenge_method: 'S256' }

# Get the authorization URL that the user must visit in the browser.
auth_url = (client.authorization_url redirect_uri).to_s

# Open `auth_url` in a browser window, and retrieve `code` from the query in the callback. Once you have the code,
# copy into the following lower-level `http_proxy` method rather than using `exchange_code_for_token`:

client.request_with_retry :post, 
	'/oauth/token', 
	client_id: <client id>, 
	client_secret: <client secret>, 
	grant_type: 'authorization_code', 
	code: <code from the callback URL>, 
	redirect_uri: <redirect URI>, 
	code_verifier: code_verifier
```

The key is that last part there. The above is what we're hoping to wrap up with a couple helpers and a method that supports PKCE without having to use the lower-level call.

**Comment by mellowfish** [comment]
Should I just close my PR then?

**Comment by stevehobbsdev** [comment]
I think that makes sense, thanks. While we will be adding support, we're not sure of the best approach yet.

**Comment by mellowfish** [comment]
Thanks for working on this!

**Comment by mellowfish** [comment]
@stevehobbsdev did PKCE support ever land? Are there any updates on when this might come?
