### ISSUE TITLE
Unable to fetch connections with multiple strategy with current implementation

### ISSUE THREAD

**Issue by benoittgt** [auth0/ruby-auth0#309]
Hello

My issue if a follow up of this [community discussion](https://community.auth0.com/t/filter-multiple-type-of-connections/73915)

We want to be able to fetch multiple connections with multiple strategies like [in the documentation](https://auth0.com/docs/api/management/v2#!/Connections/get_connections).

With the current implementation is not possible because `strategy` in `get_connection` is just a string. A workaround is to do this: 
```ruby
auth0_client.get(auth0_client.send(:connections_path), RestClient::ParamsArray.new([[:strategy, 'samlp'], [:strategy, 'waad']]) )
```
Also [body processing](https://github.com/auth0/ruby-auth0/blob/8df16c3c03fab8e499e1104a875140dfa33ac545/lib/auth0/mixins/httpproxy.rb#L20) needs to be replace with something like:

```ruby
          body = body.delete_if { |_, v| v.nil? } if body.respond_to?(:delete_if)
```

It needs more work because if we want to pass more parameters it is getting more complicated.

Do you think the gem could evolve to handle this type of call?

🌮 

cc @rouaneta

**Comment by stevehobbsdev** [comment]
Thanks for your patience here @benoittgt - certainly looks like something you should be able to do without resorting to that workaround.

Let me add it to our internal tracker and we'll prioritize it in. Thanks for raising

**Comment by stevehobbsdev** [comment]
@benoittgt I've investigated internally and it seems the team who own this part of the API are looking to see what they can do to make this more consistent with other endpoints that accept arrays and have this work. We'd prefer to see that change materialise on the server first before implementing a workaround in the SDK that may not be needed. As such, please continue to use the workaround you have for now.

Unfortunately I don't have a timeline for a fix but if the situation changes, I will try to let you know.
