### ISSUE TITLE
client_id parameter of Retrieve device credentials API is optional, but client_id argument of device_credentials method is required

### ISSUE THREAD

**Issue by shibayu36** [auth0/ruby-auth0#319]
### Describe the problem
* [Retrieve device credentials API document](https://auth0.com/docs/api/management/v2#!/Device_Credentials/get_device_credentials) says that all of parameters including client_id are optional
* But [device_credentials method](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/v2/device_credentials.rb#L27) requires that client_id must not be empty
* I want to get all of specified user's device credentials by user_id, but I cannot do it because client_id is required

### What was the expected behavior?
all of arguments of device_credentials method are optional.  I want to call this method like following.

```ruby
client = Auth0Client.new(
  client_id: auth0_config[:auth0_client_id],
  client_secret: auth0_config[:auth0_client_secret],
  domain: auth0_config[:auth0_api_domain],
)
client.device_credentials(
  nil,
  { user_id: '1' }
)
```

### Reproduction

Following code raises `Auth0::InvalidParameter: Must supply a valid client_id`
```ruby
client = Auth0Client.new(
  client_id: auth0_config[:auth0_client_id],
  client_secret: auth0_config[:auth0_client_secret],
  domain: auth0_config[:auth0_api_domain],
)
client.device_credentials(
  nil,
  { user_id: '1' }
)
```

### Environment

- **Version of this library used:** 5.6.1
- **Which framework are you using, if applicable:** Ruby on Rails
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Thanks for pointing this out, it does look like that `user_id` is actually a required property whereas `client_id` appears to be optional in the API, but you're right that the SDK doesn't allow for it.

I think we can do a couple of things in a non-breaking way; either allow `nil` to be specified for `client_id`, or add a new method like `device_credentials_for_user(user_id, options = {})`, which is more representative of how the API is actually working. I'm leaning toward the first option, currently as having the two methods might be confusing.

I'll raise a PR.

**Comment by shibayu36** [comment]
> it does look like that user_id is actually a required property whereas client_id appears to be optional in the API, but you're right that the SDK doesn't allow for it.

`user_id` does not seems to be required because the following returns response.

```
curl -H "Authorization: Bearer ..." https://{domain}/api/v2/device-credentials
```

But it looks good that we create `device_credentials_for_user` because the main use cases of this API are following

* fetching device_credentials by user_id
    * for example, we use it when we want to make a user signed-out from all Auth0 Applications(Clients)
* fetching all credentials by client_id
    * for example, we use it when we want to make users using specified client_id signed-out forcefully because we find this client has vulnerability which causes refresh_token steal

**Comment by shibayu36** [comment]
> I think we can do a couple of things in a non-breaking way; either allow nil to be specified for client_id, or add a new method like device_credentials_for_user(user_id, options = {}), which is more representative of how the API is actually working. I'm leaning toward the first option, currently as having the two methods might be confusing.

I also think the first option is better this time because of same reason of `either allow nil to be specified for client_id`

**Comment by shibayu36** [comment]
I made a pull request to solve this issue. https://github.com/auth0/ruby-auth0/pull/321

Please review it 😄
