### ISSUE TITLE
RS256 JWKS cache thrashes when using multiple Auth0 clients/tenants in same application.

### ISSUE THREAD

**Issue by rmm5t** [auth0/ruby-auth0#324]
### Describe the problem

`Auth0::Algorithm::RS256` [attempts to cache the well-known JWKS](https://github.com/auth0/ruby-auth0/blob/v5.7.0/lib/auth0/mixins/validation.rb#L313-L326). It does this using a class instance variable to store a `Zache` instance and places the JWKS into the cache using `:jwks` as the cache-key.

This works as expected if there is only one Auth0 client and one Auth0 tenant per runtime, but as soon as an application needs more than one Auth0 tenants, [this cache automatically invalidates itself as the two Auth0 clients compete for the cache](https://github.com/auth0/ruby-auth0/blob/v5.7.0/lib/auth0/mixins/validation.rb#L71-L75) (different well-known JWKS and different `kid`s).

Because the cache invalidates itself, this results in unnecessary and slow HTTP requests to fetch the well-known JWKS each time a different Auth0 client is used with a different Auth0 domain (tenant). This results in very slow JWT validation, because the well-known keys are rarely cached if both tenants are actively used. The cache thrashes and results in unnecessary web requests while validating JWT tokens.

### What was the expected behavior?

JWT validation should be fast and cache the well-known JWKS per Auth0 tenant (JWKS URL).

A potential solution to this might be to make the JWKS cache to be more specific to the domain of the JWKS URL. Perhaps the cache-key should be the URL of the JWKS URL instead of just `:jwks`.

### Reproduction

1. Start with two Auth0 tenants.
2. Configure two Auth0 clients (one for each tenant)  using RS256.
3. Validate a JWT token using the first tenant (note how it is slow while waiting to fetch the JWKS)
4. Validate the same JWT token again (note how it validates quickly)
5. Validate a second JWT token against second tenant (note how it is slow while waiting to fetch the new JWKS).
6. Validate the first JWT token again against the first tenant (note how it is slow, because the JWKS is no longer cached).

### Environment

- Version of this library used: **5.5.0** and **5.7.0**
- Which framework are you using, if applicable: **Rails**

### ~~Ask~~

~~I'd like to submit a PR to tie the JWKS cache-key to the JWKS URL instead of `:jwks`. Is that something that would be appreciated, and do you think that would be the best approach to solve this problem?~~

### See #325

**Comment by stevehobbsdev** [comment]
Thanks, seems reasonable. I've reviewed the PR 👍🏻
