### ISSUE TITLE
Connections Endpoint is missing `include_totals` parameter

### ISSUE THREAD

**Issue by norascheuch** [auth0/ruby-auth0#349]
### Describe the problem you'd like to have solved

The official auth0 api endpoint [get_connections](https://auth0.com/docs/api/management/v2/#!/Connections/get_connections) has a paramter `include_totals`. Since the endpoint is paginated the totals are needed to get all connections sensibly. 

### Describe the ideal solution

Add `include_totals` as a parameter in the [connections method](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/v2/connections.rb#L18)

## Alternatives and current work-arounds
Know how many you have and loop over that, make an educated guess, just using `my_client.get('api/v2/connections', parameters_including_the_totals)` does not work for me (`getaddrinfo': Failed to open TCP connection).

### Additional information, if any

I would be happy to make the contribution myself?!

**Comment by stevehobbsdev** [comment]
Thanks for the call out, I've raised #357 to fix this 👍🏻
