### ISSUE TITLE
Duplicate Passwordless email

### ISSUE THREAD

**Issue by Guuri11** [auth0/ruby-auth0#356]
### Describe the problem

I'm implementing a passwordless flow in my ruby on rails app. But the user receives duplicate magic links from Auth0. This is a problem because the user enters to the first email & it is invalid because he receives a new one. So it provoques an UX issue

### What was the expected behavior?

Call _**Client.start_passwordless_email_flow**_ endpoint and send just ONE email, without duplicate the magic link email.

### Reproduction
This is the following code:
```
email = "foo@bar.com"
user = auth0_client.users_by_email(email)[0]
user ||= auth0_client.create_user(
      "email",
      {
        name: email,
        email: email
      }
    )
Auth0Helper.add_metadata_to_user(user, exam) # This helper is for adding needed metadata to the user, using the patch_user method
auth0_client.start_passwordless_email_flow(email, "link")
```

> Where possible, please include:

It duplicates the email when _auth0_client.create_user is called_

- **Version of this library used:** last one
- **Which framework are you using, if applicable:** ruby on rails 6
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by stevehobbsdev** [comment]
Thanks for the report. Just to clarify, the email is being sent from Auth0 server as a result of this call. Are you able to confirm that only one request is actually sent across the wire to Auth0? Also, is the user account being used linked to another account?

I ask because one way you can have multiple passwordless emails being sent is in a case where you have linked multiple accounts together.

**Comment by Guuri11** [comment]
@stevehobbsdev thanks for reply. I could solve the issue. Gmail was doing a second request with a bot to verify if it was a malicious link. To fix it blocked second requests for 1 minute & I added this meta in the html template from my app

`<meta name="robots" content="nofollow">
<meta name="googlebot" content="noindex">`
