### ISSUE TITLE
validate_id_token fails to validate non-OIDC compliant access tokens due to azp

### ISSUE THREAD

**Issue by btalayeminaei** [auth0/ruby-auth0#363]
### Describe the problem you'd like to have solved

Currently, the only way to validate tokens is via the `validate_id_token` method in `Auth0::Client`. While it possible to use this method to validate an Auth0 issued `Access Token`, validation fails if the token is not OIDC compliant. If I understand it correctly, access tokens are not required to be OIDC compliant. The particular issue we are running into is with the [azp validation logic](https://github.com/auth0/ruby-auth0/blob/6f11a5da783d9fa9744a62aaaf27ec42d6476d96/lib/auth0/mixins/validation.rb#L121) for the following token:
```js
{
  "iss": "https://caribou-customers-dev.us.auth0.com/",
  "sub": "auth0|52232b06-1991-4a70-b8b2-80695441a19b",
  "aud": [
    "https://api.caribou-dev.com/",
    "https://caribou-customers-dev.us.auth0.com/userinfo"
  ],
  "iat": 1658964155,
  "exp": 1659050555,
  "azp": "09LZ94hgQKfdYe0NWij0bAsWdiDJcKO4",
  "scope": "openid profile email"
}
```

Since there are multiple audiences, the validation logic checks that the `azp` field matches the expected audience. However, Auth0 sets the field to the client_id.

### Describe the ideal solution

Here are a couple of solutions that we thought of:

-  Add a specific method for `Access Token` validation based on [Auth0 guidance](https://auth0.com/docs/secure/tokens/access-tokens/validate-access-tokens)
-  Allow caller of the existing `validate_id_token` method to skip `azp` validation

## Alternatives and current work-arounds

Currently, we monkey patch the `validate_azp` method in our codebase.
```rb
class Auth0::Mixins::Validation::IdTokenValidator
  def validate_azp(claims, expected); end
end
```

## Additional Information
semi-relevant resources
https://community.auth0.com/t/access-token-has-two-audiences/71041
https://github.com/auth0/auth0-PHP/issues/422#issuecomment-582097775

**Comment by stevehobbsdev** [comment]
Thanks for the report @btalayeminaei. As the method suggests, its intention is to validate ID tokens and we validate these for OIDC compliance. While it _could_ accept an access token (if you have an access token in JWT format), that's not what it's intended for.

As a feature, it's unlikely something that we'll add to this SDK, as this SDK is intended to be used in a client app (access tokens are intended for and to be validated by a resource server - that scenario is out of scope for this SDK). The recommendation is that you either write some custom validation (or use a third-party intended to validate access tokens), or monkey patch it as you have done, at your own risk.

I appreciate that's not ideal but hopefully you understand where I'm coming from.

**Comment by kwstannard** [comment]
Is there an SDK specifically for resource servers?

**Comment by wontonst** [comment]
yeah I'm surprised auth0 does not have a SDK for resource servers that takes into account the nuances of the access_token issued by auth0
