### ISSUE TITLE
Update to latest jwt gem version 2.4.*

### ISSUE THREAD

**Issue by eric-christian** [auth0/ruby-auth0#369]
Hello

We use the jwt gem within our rails app and noticed that we are unable to update the jwt gem to the latest version. The jwt gem's latest version is currently [2.4.1](https://github.com/jwt/ruby-jwt/releases). 

Auth0 locks the jwt gem to `~> 2.3.0` so only changes to the patch part of the semver are accepted. But the semver of the jwt gem had an increment on the minor part. Can this be changed to `~> 2.3` within the gemspec?

Best regards,
Eric

**Comment by stevehobbsdev** [comment]
I'll have another look into this. I did try to update this dependency recently but was met with several errors.

**Comment by raldred** [comment]
We need openssl 3 support so are having issues with not being able to update to jwt 2.5.0
So other usage of JWT in our app that uses JWKs errors.
```
<OpenSSL::PKey::PKeyError: rsa#set_key= is incompatible with OpenSSL 3.0>
```
