### ISSUE TITLE
Implement API v2

### ISSUE THREAD

**Issue by ignaciojonas** [auth0/ruby-auth0#38]
We took a look to the API V2 and found some endpoints that are not implemented.

Our plan is to implement those endpoints and review the already implemented ones.
### Endpoints to be implemented
* Device Credentials (3 endpoints)
* Rules (5 endpoints)
* Email (4 endpoints)
* Tickets (2 endpoints)

### Methods to be implemented
* Jobs
 * create_job

    This method needs to be implemented using multipart upload, HTTParty doesn't support it. We think that we can switch to use [HTTMultiParty](https://github.com/jwagener/httmultiparty) which supports multipart upload.

We also found that the API code is not documented and the code style can be improved. We would suggest to:
* Add documentation to the code, we could use [TomDoc](http://tomdoc.org/), recommended by [Github ruby style guide](https://github.com/styleguide/ruby)
* Integrate [Rubocop](https://github.com/bbatsov/rubocop) to improve the API code style.

Regarding the integration tests, we would like to add more tests for all the endpoints in the API.
Currently just the clients, connections and users are tested. We are planning to create integration tests for all endpoints, against the real Auth-0 API in order to have a better integration scenario.

We'll start working on fixing the code style in order to clean the code base first.

We would love to hear your feedback on any of these topics.

**Comment by npetkov** [comment]
Hi, our team just finished integrating Auth0 in a Rails application, but we're still missing some features in the ruby bridge, like ticket and job creation. There has been quite some movement in the v2 branch recently, so we're wondering if you're planning a release soon?

**Comment by joshRpowell** [comment]
+1

**Comment by dentarg** [comment]
I just want to note that https://github.com/jwagener-soundcloud/httmultiparty now seems to be unmaintained, might become a problem in the long-term.
