### ISSUE TITLE
Remove the examples directory from this repository

### ISSUE THREAD

**Issue by jfromaniello** [auth0/ruby-auth0#4]
Read carefully. 

Remove the examples directory from this repository because it is completely unrelated to this project:

-  `examples/ruby-on-rails-webapp` is a **omniauth-auth0** example, so it should go straight to the examples directory of omniauth-auth0.
-  `examples/ruby-on-rails-api` is an **ruby-jwt** example, but because this is a general purpose library and not only for auth0, and most importantly we don't own that repository, create a new repository `auth0/rails-jwt-example` or `rails-jwt-seed`.

Modify the example packager/seed project/docs etc with the new links.

**Comment by hzalaz** [comment]
Already removed
