### ISSUE TITLE
Support for exchanging OTP for Access Token

### ISSUE THREAD

**Issue by theodoretliu** [auth0/ruby-auth0#422]
### Describe the problem you'd like to have solved

I'd like to use the Ruby client to exchange SMS OTP's for Access Tokens. This flow is documented [here](https://auth0.com/docs/api/authentication#authenticate-user) and the passwordless flow start is already supported!

### Describe the ideal solution

An API akin to `client.exchange_otp_for_token(username, code, realms...)` would be great!

## Alternatives and current work-arounds

I can currently make the `POST` manually using Faraday or other HTTP libraries.

**Comment by stevehobbsdev** [comment]
Thanks for the feature request @theodoretliu, it's in our backlog to investigate 👍

**Comment by stevehobbsdev** [comment]
Thanks for your patience @theodoretliu , this is now available in [v5.11.0](https://github.com/auth0/ruby-auth0/releases/tag/v5.11.0) 👍🏻
