### ISSUE TITLE
Version 4 changes

### ISSUE THREAD

**Issue by Soliah** [auth0/ruby-auth0#54]
Can the version 4 changes be added to the changelog and a tag pushed. Would like to know what's changed.

**Comment by LindseyB** [comment]
I'm curious about this too, looks like there hasn't been a new release since 2015 would be nice if we could get a new release cut.

**Comment by chazu** [comment]
Agreed on both points above - we need to know whats in the release before it is useful, and we also have some change requests which have been merged that we need released badly.
