### ISSUE TITLE
Using inside of a Rails API

### ISSUE THREAD

**Issue by brandonmikeska** [auth0/ruby-auth0#55]
Is there an example of this being used inside of a Rails API project? All of the rails api projects just have authenticating the current user.

**Comment by brandonmikeska** [comment]
I keep getting a scope error now but I don't see anywhere for me to set the scope.

**Comment by mrrobby** [comment]
I agree, there needs to be more documentation on this one.  I had to search through the code to get something working.  I had success with something similar to this: 
```
def signup_with_auth0!(params,user)
   auth0 = Auth0Client.new( :token => Rails.application.secrets.auth0_api_token,
				            :domain => "yourdomain.auth0.com",
				            :api_version => 2)
   auth0.signup(user.email,params[:password],"Your-UserPass-Authentication")
end
```

Of course, you could start with params[:email], but you may want to do some other checks first.

After, you can follow the [v2 link to their API console](https://auth0.com/docs/api/v2) and generate your token there with the specific tasks you want to accomplish.  There's more methods like signup in the [endpoints file](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/authentication_endpoints.rb).  Otherwise, you can build your own client and use the endpoints provided and accessible by the token you generate.

**Comment by oyeanuj** [comment]
@brandonmikeska @mrrobby Where did you guys end up with this? I am trying to implement it within a rails-api set up and unclear on some of the details. Is there a gist/repo that anyone could share?

**Comment by brandonmikeska** [comment]
@oyeanuj I got a working example but stopped using rails all together and just went with Firebase. If I find time I will try to create a small repo or gists on what I did. It's not too complicated but basically I created a base controller that would check for the token and inherited the base controller on any controller than needed authentication.

I also created an @auth0 object that was available so I didn't have to set it up every time in an action. Pretty basic stuff. Is that what you are looking for?

**Comment by oyeanuj** [comment]
@brandonmikeska Thank you, that was the kind of information I was looking for! If you can provide any sort of gists for what you described, that would be super helpful and make it much easier to start!

@ignaciojonas - any chance that this could be part of the official documentation?

**Comment by ignaciojonas** [comment]
Hi @oyeanuj, we are currently working on updating all the rails samples. So far we have completed those for a basic rails web app, they are already available [here](https://github.com/auth0-samples/auth0-rubyonrails-sample). Sample-02 might help you, although is not exactly aiming to an API Project.

**Comment by oyeanuj** [comment]
@ignaciojonas Thanks for the response. The tutorial on that link doesn't seem to work - https://auth0.com/docs/quickstart/webapp/rails/02-custom-login. Is there an updated link for this?

**Comment by ignaciojonas** [comment]
@oyeanuj It seems that the tutorial is not merged yet. You can take a look to the code [here](https://github.com/auth0-samples/auth0-rubyonrails-sample/tree/master/02-Custom-Login)

**Comment by oyeanuj** [comment]
@ignaciojonas thanks! not to extend this thread further, but are there any rails one with an example of password-less magic link authentication?

**Comment by joshcanhelp** [comment]
Just FYI for anyone looking ... we have a quickstart for a Ruby API:

https://auth0.com/docs/quickstart/backend/ruby

... and one for Rails:

https://auth0.com/docs/quickstart/backend/rails
