### ISSUE TITLE
Not possible to have V1 and V2 clients at the same time

### ISSUE THREAD

**Issue by psteininger** [auth0/ruby-auth0#60]
Apparently header information is being clobbered between 2 separate instances of clients.

I need V2 client for user management, and V1 client to generate impersonation links.
When I have this:
```ruby
Rails.application.auth0_api_client = Auth0Client.new(
    :api_version => 2,
    :token => ENV['AUTH0_JWT_TOKEN'],
    :domain => ENV['AUTH0_DOMAIN']
)

Rails.application.auth0_auth_client = Auth0Client.new(
    :api_version => 1,
    :domain => ENV['AUTH0_DOMAIN'],
    :client_id => ENV['AUTH0_API_KEY'],
    :client_secret => ENV['AUTH0_API_SECRET']
)
```
`Rails.application.auth0_api_client` acts as if it was the latter. This is potentially a security issue, on top of not allowing us to manage users and provide a link to impersonate. At the root of this issue is that V2 JWT token does not work with impersonation API, which _should_ be in V2 afterall.

**Comment by psteininger** [comment]
The issue stems from using `HTTParty` class method `headers`. The headers should have been isolated to an instance variable and added in `perform_request`. 
I have a VERY hacky workaround, but it works. Since the headers are set at class level, it's easy to create 2 subclasses of the `Auth0Client` and use them to create instances. 
```ruby
class Auth0ClientV2 < Auth0Client; end
class Auth0ClientV1 < Auth0Client; end

Rails.application.auth0_api_client = Auth0ClientV2.new(
    :api_version => 2,
    :token => ENV['AUTH0_JWT_TOKEN'],
    :domain => ENV['AUTH0_DOMAIN']
)

Rails.application.auth0_auth_client = Auth0ClientV1.new(
    :api_version => 1,
    :domain => ENV['AUTH0_DOMAIN'],
    :client_id => ENV['AUTH0_API_KEY'],
    :client_secret => ENV['AUTH0_API_SECRET']
)
```

**Comment by Amialc** [comment]
@psteininger impersonated links works with v2 now (https://github.com/auth0/ruby-auth0/pull/62)
