### ISSUE TITLE
Bug?: `result` from auth0/mixins/httpproxy.rb returns 'nil'

### ISSUE THREAD

**Issue by kevinzwhuang** [auth0/ruby-auth0#88]
I saw this error from Auth0Client a couple of times in the past week:

`undefined method `code' for nil:NilClass`

`auth0/mixins/httpproxy.rb in block (2 levels) in <module:HTTPProxy> at line 20`

https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/mixins/httpproxy.rb#L20

![screen shot 2017-04-25 at 11 11 30 am](https://cloud.githubusercontent.com/assets/7256178/25400713/4447bf04-29a8-11e7-821b-be61f7bcb52c.png)

For some reason, `result` is `nil` in httpproxy.rb here. 

This occured from a call to `Auth0Client.new(**options**).user(**user_uid**)`. I haven't been able to reproduce this myself, so I'm not sure what the cause is here. Attempts to re-use the same user uid manually return successful results.

**Comment by joshcanhelp** [comment]
Very delayed response here ... I'm not sure how to reproduce this. Possibly a network issue if it's intermittent?
