### ISSUE TITLE
Client specific post email verification redirect URL problem in V2

### ISSUE THREAD

**Issue by tadejm** [auth0/ruby-auth0#92]
Greetings fellow Auth0 geeks,

I have an existing Auth0 account with multiple clients and [conditional post email verification redirects](https://auth0.com/docs/email/custom#custom-redirect) specified through the Auth0 dashboard.
When triggering a resend verification email job via the Ruby V2 client, the redirect to URL points to the default URL, not the one specified for the given `client_id`.

This is not the behavior in the V1 implementation where the `client_id` is correctly applied and the redirect follows to the specified URL.

Looking at the docs for [Send a "verify email address" email](https://auth0.com/docs/api/management/v2#!/Jobs/post_verification_email) a `client_id` body attribute is accepted, where as [the Ruby implementation](https://github.com/auth0/ruby-auth0/blob/master/lib/auth0/api/v2/jobs.rb#L42-L49) (to my understanding) does not apply the `client_id`:

```ruby
def send_verification_email(user_id)
  raise Auth0::InvalidParameter, 'Must specify a user id' if user_id.to_s.empty?
  request_params = {
    user_id: user_id
  }
  path = "#{jobs_path}/verification-email"
  post(path, request_params)
end
```

Naively, should we add an optional `client_id` argument and add it to the `request_params` if the value is present?

Thanks for your feedback

**Comment by unkw** [comment]
I have the same problem , my {application.callback_domain} is empty string and get error as: {"name":"BadRequestError","code":"invalid_result_url","description":"invalid result url: /confirmation-email?...20once&success=false","statusCode":400}

**Comment by joshcanhelp** [comment]
Apologies for the long delay in addressing this. Thank you for the very complete report here. As soon as #140 is merged in, I'll add that parameter and release it with [v4.6.0](https://github.com/auth0/ruby-auth0/milestone/2).

**Comment by tadejm** [comment]
Awesome! Thanks @joshcanhelp :purple_heart:
